module VerifyExamples.Tracery.FromJson3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Tracery exposing (..)
import Result.Extra
import Random
import Json.Decode



generate : Int -> String -> String
generate seed json =
    json
        |> Tracery.fromJson
        |> Result.Extra.unpack
            Json.Decode.errorToString
            (\grammar ->
                Random.step (Tracery.run grammar) (Random.initialSeed seed)
                    |> Tuple.first
            )



spec3 : Test.Test
spec3 =
    Test.test "#fromJson: \n\n    \"\"\"\n    { \"origin\": [\"I have two pets: a #pet# and a #pet#\"]\n    , \"pet\": [\"cat\",\"dog\",\"fish\",\"parrot\"]\n    }\n    \"\"\"\n    |> generate 42\n    --> \"I have two pets: a dog and a cat\"" <|
        \() ->
            Expect.equal
                (
                """
                { "origin": ["I have two pets: a #pet# and a #pet#"]
                , "pet": ["cat","dog","fish","parrot"]
                }
                """
                |> generate 42
                )
                (
                "I have two pets: a dog and a cat"
                )