module VerifyExamples.Tracery.FromJson1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Tracery exposing (..)
import Result.Extra
import Random
import Json.Decode



generate : String -> String
generate json =
    json
        |> Tracery.fromJson
        |> Result.Extra.unpack
            Json.Decode.errorToString
            (\generator ->
                Random.step generator seed
                    |> Tuple.first
            )
seed : Random.Seed
seed =
    Random.initialSeed 40



spec1 : Test.Test
spec1 =
    Test.test "#fromJson: \n\n    \"\"\"\n    { \"origin\": \"#petPraise# and #petPraise#\"\n    , \"petPraise\": \"#praise#\"\n    , \"praise\" : [\"my dog loves to bark at #objects#\",\"my cat loves to watch #objects#\"]\n    , \"objects\": [ \"cars\", \"trees\", \"birds\", \"people\" ]\n    }\n    \"\"\"\n    |> generate\n    --> \"my cat loves to watch cars and my cat loves to watch birds\"" <|
        \() ->
            Expect.equal
                (
                """
                { "origin": "#petPraise# and #petPraise#"
                , "petPraise": "#praise#"
                , "praise" : ["my dog loves to bark at #objects#","my cat loves to watch #objects#"]
                , "objects": [ "cars", "trees", "birds", "people" ]
                }
                """
                |> generate
                )
                (
                "my cat loves to watch cars and my cat loves to watch birds"
                )