module VerifyExamples.Tracery.FromJson1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Tracery exposing (..)
import Result.Extra
import Random
import Json.Decode



generate : String -> String
generate json =
    json
        |> Tracery.fromJson
        |> Result.Extra.unpack
            Json.Decode.errorToString
            (\generator ->
                Random.step generator seed
                    |> Tuple.first
            )
seed : Random.Seed
seed =
    Random.initialSeed 40



spec1 : Test.Test
spec1 =
    Test.test "#fromJson: \n\n    \"\"\"\n    { \"origin\": \"#sentence# and #sentence#\"\n    , \"sentence\":\n        [ \"my #favoritePet# is better than my neighbors #pet#\"\n        , \"my #favoritePet# is worse than my neighbors #pet#\"\n        ]\n    , \"favoritePet\": \"#pet#\"\n    , \"pet\": [\"cat\",\"dog\",\"fish\",\"parrot\"]\n    }\n    \"\"\"\n    |> generate\n    --> \"my cat is worse than my neighbors dog and my cat is better than my neighbors parrot\"" <|
        \() ->
            Expect.equal
                (
                """
                { "origin": "#sentence# and #sentence#"
                , "sentence":
                    [ "my #favoritePet# is better than my neighbors #pet#"
                    , "my #favoritePet# is worse than my neighbors #pet#"
                    ]
                , "favoritePet": "#pet#"
                , "pet": ["cat","dog","fish","parrot"]
                }
                """
                |> generate
                )
                (
                "my cat is worse than my neighbors dog and my cat is better than my neighbors parrot"
                )