module VerifyExamples.Tracery.FromJson5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Tracery exposing (..)
import Result.Extra
import Random
import Json.Decode



generate : String -> String
generate json =
    json
        |> Tracery.fromJson
        |> Result.Extra.unpack
            Json.Decode.errorToString
            (\generator ->
                Random.step generator seed
                    |> Tuple.first
            )
seed : Random.Seed
seed =
    Random.initialSeed 40



spec5 : Test.Test
spec5 =
    Test.test "#fromJson: \n\n    \"\"\"\n    { \"origin\": \"The \\\\\\\\# and \\\\\\\\\\\\\\\\ characters need to be escaped.\"}\n    \"\"\"\n    |> generate\n    |> Debug.log \"exposing\"\n    --> \"The # and \\\\ characters need to be escaped.\"" <|
        \() ->
            Expect.equal
                (
                """
                { "origin": "The \\\\# and \\\\\\\\ characters need to be escaped."}
                """
                |> generate
                |> Debug.log "exposing"
                )
                (
                "The # and \\ characters need to be escaped."
                )