module VerifyExamples.Tracery.SentenceParser0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Tracery exposing (..)
import Parser







spec0 : Test.Test
spec0 =
    Test.test "#sentenceParser: \n\n    \"My #Pet# is awesome\"\n    |> Parser.run sentenceParser\n    --> Ok [Print \"My \", Choose \"Pet\", Print \" is awesome\"]" <|
        \() ->
            Expect.equal
                (
                "My #Pet# is awesome"
                |> Parser.run sentenceParser
                )
                (
                Ok [Print "My ", Choose "Pet", Print " is awesome"]
                )